/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bizent;

import javax.swing.JTable;

/**
 *
 * @author Nahuel
 */
public class Inv extends javax.swing.JPanel {

    /**
     * Creates new form Inv
     */
    public Inv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inversionesTable = new javax.swing.JTable();
        btnRealizarInv = new javax.swing.JButton();
        btnCobrarInv = new javax.swing.JButton();

        inversionesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Plazo Fijo Santander Rio", "Plazo Fijo Tradicional", "01/09/2013", "2000", "30/09/2013"},
                {"Plazo fijo ICBC", "Plazo Fijo Tradicional", "01/06/2013", "1000", "30/06/2013"},
                {"Plazo fijo Santander Rio", "Plazo Fijo Tradicional", "15/08/2013", "1500", "14/09/2013"}
            },
            new String [] {
                "Descripción", "Tipo de Inversión", "Fecha de Creación", "Inversión Inicial", "Vencimiento"
            }
        ));
        jScrollPane2.setViewportView(inversionesTable);

        btnRealizarInv.setText("Realizar Inversión");
        btnRealizarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarInvActionPerformed(evt);
            }
        });

        btnCobrarInv.setText("Realizar Cobro");
        btnCobrarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarInvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRealizarInv)
                .addGap(18, 18, 18)
                .addComponent(btnCobrarInv)
                .addGap(86, 86, 86))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRealizarInv)
                    .addComponent(btnCobrarInv))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarInvActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddInversion dialog = new AddInversion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(null); // Center on the screen
                dialog.setVisible(true);
                updateInversionesJTable();
            }
        });
    }//GEN-LAST:event_btnRealizarInvActionPerformed

    private void btnCobrarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarInvActionPerformed

        final int selectedRow = inversionesTable.getSelectionModel().getLeadSelectionIndex();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PFRealizarCobrosInv dialog = new PFRealizarCobrosInv(new javax.swing.JFrame(), true, Integer.parseInt(inversionesTable.getValueAt(selectedRow, 0).toString()), inversionesTable.getValueAt(selectedRow, 1).toString(),inversionesTable.getValueAt(selectedRow, 2).toString(), inversionesTable.getValueAt(selectedRow, 5));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //                        System.exit(0);
                    }
                });
                dialog.setLocationRelativeTo(null); // Center on the screen
                dialog.setVisible(true);
                updateInversionesJTable();
            }
        });
    }//GEN-LAST:event_btnCobrarInvActionPerformed

    
    public static void updateInversionesJTable() {
        inversionesTable.getColumnModel().getColumn(0).setMinWidth(0);
        inversionesTable.getColumnModel().getColumn(0).setMaxWidth(0);
        inversionesTable.getColumn("Inversión inicial").setCellRenderer(new DecimalRenderer("###,##0.00"));
        inversionesTable.getColumn("Fecha de creación").setCellRenderer(new DateRenderer("dd-MM-yyyy"));
        inversionesTable.getColumn("Vencimiento").setCellRenderer(new DateRenderer("dd-MM-yyyy"));
    }
    public static JTable getTable()
    {
        return inversionesTable;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobrarInv;
    private javax.swing.JButton btnRealizarInv;
    private static javax.swing.JTable inversionesTable;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
